# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-08 02:34
from __future__ import unicode_literals

from django.db import migrations

import csv


def rater_stat(apps, schema_editor):
    Rater = apps.get_model("ratings_app", "Rater")

    with open("u.user") as outfile:
        rater = csv.DictReader(outfile, fieldnames=["user_id", "age", "gender", "occupation", "zip_code"],
                               delimiter="|")

        for row in rater:
            Rater.objects.create(user_id=int(row['user_id']), age=int(row['age']),
                                 gender=row['gender'], occupation=row['occupation'], zip_code=row['zip_code'])


class Migration(migrations.Migration):

    dependencies = [
        ('ratings_app', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(rater_stat)
    ]
